/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ParkiT (void);
GtkWidget* create_Ajouter_reservation_ (void);
GtkWidget* create_supprimer_reservation (void);
GtkWidget* create_reserver_service_ (void);
GtkWidget* create_supprimer_service_ (void);
GtkWidget* create_Authentification (void);
GtkWidget* create_Affichage (void);
